name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build_macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment and compile
        run: |
          mkdir -p artifacts
          cd src  # Change to your source code directory
          gcc cpuid_check.c -o ../artifacts/cpuid_check
          # Add more compilation commands for other files if needed

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChipInspect_macOS
          path: artifacts/cpuid_check

  build_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment and compile
        run: |
          mkdir -p artifacts
          cd src  # Change to your source code directory
          gcc cpuid_check.c -o ../artifacts/cpuid_check
          # Add more compilation commands for other files if needed

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChipInspect_Linux
          path: artifacts/cpuid_check

  build_windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment and compile
        shell: bash
        run: |
          mkdir -p artifacts
          cd src  # Change to your source code directory
          gcc cpuid_check.c -o ../artifacts/cpuid_check.exe
          # Add more compilation commands for other files if needed
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChipInspect_Win64
          path: artifacts/cpuid_check.exe
